### ISSUE TITLE
Suggestion for Section II of Finalizing Setup

### ISSUE THREAD

**Issue by TheOriginalGeez** [hacks-guide/Guide_3DS#1680]
Add a warning: "If, after following this guide, a system update is available be sure to update Luma first."

**Comment by MechanicalDragon0687** [comment]
Section II is the update section, as such this would better suited to the Information section at the bottom. If after updating in section II there is another update, updating again would be a good idea since a cached update would be installed first.  In addition, a new Luma update is rarely available at the time when a new system update is released, so initially this instruction would be useless while after a few days, a Luma update may be available (assuming an update was necessary)
