### ISSUE TITLE
Incorrect Information about Browserhax 2020

### ISSUE THREAD

**Issue by dwain12435** [hacks-guide/Guide_3DS#1796]
The Get Started page says that Browserhax 2020 only works on 11.13, when it actually works from 11.10 to 11.13. Also, the Homebrew Launcher Alternative Methods page says that browserhax only works on versions up to 11.0, which isn't true (Browserhax 2020).

**Comment by GlaZedBelmont** [comment]
It seems you confused browserhax **2020** with old and dead browserhax.

**Comment by techmuse8** [comment]
And referring to Issue #1787, even if you were on that version, you would get update nagged.

**Comment by ihaveamac** [comment]
The browser wouldn't do that right now because it has its own update check. It was last updated 11.9.0-42.

**Comment by lilyuwuu** [comment]
While browserhax 2020 would indeed work between 11.10 and 11.12, there's a number of reasons that it is not listed:

- The way versioning works already confuses people as-is -- we've had many people try to follow Soundhax with 11.13 because 11.13 is numerically a smaller number than 11.3. Putting something as working "between 11.10 and 11.13" will confuse people even more.
- If you want to take "compatibility" to its logical extreme, browserhax 2020 works from 11.9 to 11.13 on USA/JPN and 11.10 to 11.13 on EUR. It is impossible to add this to the version table without unnecessarily confusing people.
- The last cartridge update firmware documented on 3dsdb is 11.9.0J. I'm not 100% sure if there are newer cartridge updates, but if there are, explicitly adding support for 11.10 to 11.12 would mean some people would have a dummy browser and be forced to update anyway.
    - We can't just say "if your browser version is between 42 and 45" because of KOR region.
- Because no 11.13 cart updates exist, we know that if the user is on 11.13 that they have a working browser (and if they don't, it's not something that can be fixed because they must have already tried updating their browser if they're on 11.13).

The only benefit to this is if someone is having issues updating from between stock 11.10 and 11.12, which I haven't seen in the wild yet. Costs still outweigh the benefits though, IMO.

**Comment by GlaZedBelmont** [comment]
See above comment

**Comment by dwain12435** [comment]
OK
