### ISSUE TITLE
Remove hardmod method!

### ISSUE THREAD

**Issue by dwain12435** [hacks-guide/Guide_3DS#1804]
The hardmod method should be removed from the guide, as ntrboot can do everything it can do and is far easier and less risky. We don't need noobs that know how to solder to think that this method is right for them, as it has resulted in multiple hardbricks.

**Comment by GlaZedBelmont** [comment]
Good thing that we don't recommend hardmods as the primary method and say that it's only for experimented users only. You'd be surprised how few people follow this method and end up having troubles with it. While you do bring up a good point: NTRBoot is easier and less risky. We can say that every method in the guide that's not an hardmod. Let's say a console is unable to update to latest version due to bad network hardware and has a defect cart slot, the only way the user would be able to install CFW would be through an hardmod.

Also a noob that knows how to solder isn't a noob at all.

Maybe it could get moved somewhere else but definitely not removed.

**Comment by dwain12435** [comment]
Hey, GlaZedBelmont, even if there was a situation in which someone happened to have bad network hardware and a broken card slot, they could still install CFW via DSiWareHax or possibly soundhax. Also, a 3DS hacking noob can be good at soldering. And if you still have another stupid reason that it shouldn't be gotten rid of, then maybe it should be taken off the main page?

**Comment by ihaveamac** [comment]
For some users it might be the only way (soundhax depends on old versions, dsiwarehax and browserhax requires internet). Maybe it doesn't need to be promoted (it isn't really promoted that much anyway), but it is not going to be removed as a method, no matter how "stupid" you might think it is.

**Comment by MechanicalDragon0687** [comment]
To add to this, there are times when a machine is hardware incapable of several other methods and hardmod may be the only way (rare, but seen).  I would agree in keeping hardmod on the page, certainly. I would concede that moving it off of the methods page and just linking it via the site nav page may be a good option to prevent irrational "I could do this" while still having the information available if needed/desired.

**Comment by PhazonicRidley** [comment]
Omg it's Randal pog
