### ISSUE TITLE
Old browser exploit isn't possible on N2DSLL (JPN) on 11.6

### ISSUE THREAD

**Issue by malvarenga123** [hacks-guide/Guide_3DS#1864]
**Pages with issue(s)**

https://3ds.hacks.guide/get-started-(new-3ds)

**Description of the issue(s)**
The guide indicates that for a New 2DS XL (LL) at firmware 11.6 one should use SSLoth-Browser exploit.
The issue is that the browser is unusable on firmware 11.6. If you try to access any page using the browser, a message saying you should update the software pops up.
Similar to what is reported here: https://gbatemp.net/threads/stumped-on-installing-cfw-on-japanese-n2dsll.580973/
Error 032-0420 happens if you use the spoofed DNS before entering the browser at least once.

The only solution, which was also mentioned in that thread, was to update to version 11.14 and then run new-browserhax-xl.

**Comment by lilyuwuu** [comment]
Aware of the issue, working on a way to resolve it. We've thrown around the following ideas so far:

- add warning about jpn n3ds under required reading, where there is currently a warning about cart updated consoles
- add warning about jpn n3ds within Section III - Launching SafeB9SInstaller, but we'd need to reword it since it just says "if you get an error, follow this troubleshooting guide"
- remove the method entirely for being more trouble than it's worth, and just tell people to update their consoles

**Comment by malvarenga123** [comment]
My vote goes to
> remove the method entirely for being more trouble than it's worth, and just tell people to update their consoles
As long as 11.14 remains the latest update, it's just easier to update and run new-browserhax-xl.

**Comment by MechanicalDragon0687** [comment]
moot point now
