### ISSUE TITLE
Simpler method to update boot9strap

### ISSUE THREAD

**Issue by Yrouel** [hacks-guide/Guide_3DS#2023]
**Pages with issue(s)**

https://3ds.hacks.guide/updating-b9s

**Description of the issue(s)**

I think it'll be easier for users to update B9S using Luma's chainloading capability instructing them to copy SafeB9SInstaller.firm to /luma/payloads, reboot the console pressing start and then to chose SafeB9S to boot and continue from there.

Also I think leaving Luma untouched in this scenario would prevent some unforeseen issue should the user mess something up

**Comment by lifehackerhansol** [comment]
Our consensus to _not_ doing this was because the Updating B9S page is more of a catch-all-fix-all page that we provide for other issues as well.

For example, if you only have Luma3DS on CTRNAND, you can't chainload SB9SI from SD. And on B9S1.0, which is what the average person following this page used to have, you can't load later versions of Luma3DS, so you have to power off and then replace `boot.firm` _anyway_.

The related pull request: #1913
