### ISSUE TITLE
Region Changing / CTRTransfer guide still only has the 11.15.0 CTRTransfer image, not the newest 11.16.0.

### ISSUE THREAD

**Issue by Hybrid-Divide** [hacks-guide/Guide_3DS#2165]
**Pages with issue(s)**

https://3ds.hacks.guide/ctrtransfer.html
https://3ds.hacks.guide/region-changing

**Description of the issue(s)**

The CTRTransfer image links are still for the old 11.15.0 firmware.
Unless I'm mistaken, the newest firmwre is needed.  Thanks.

**Comment by lilyuwuu** [comment]
The ctrtransfer links do not need to be the latest version, as users can just update to the latest version after the ctrtransfer (this is explicitly stated on the region changing page, while the ctrtransfer page links to finalizing setup which has updating as a part of it).

There have been a few times when the image has been swapped out:
- The original ctrtransfer images (iirc) were for version 9.2
- When the New 2DS came out, the images were updated to 11.5 since the new 2ds doesn't work properly on older firmwares without some patching
- While 11.15 was out, we got ahold of the data required for K/C/T regions, so all images were updated at that time

New images could be created but it's unlikely due to high effort and little benefit.

**Comment by Hybrid-Divide** [comment]
Would they still be able to use 11.15 for the CTRTransfer if they updated to the 11.16 firmware when they jailbroke their 3DS?
The guide does call for it updating to the latest version.  If this is possible, the Region Change / CTRTransfer guide should reflect that.  I just want to make sure before I proceed.  Thanks! :)

**Comment by lilyuwuu** [comment]
The current firmware of the device does not matter. The main point is that flashing a 11.15 image will bring you to 11.15 (incredibly surprising, I know). Nothing will break from having been on 11.16 beforehand.

I'm not entirely sure a note is necessary - if there was some danger, it would've been noted with a red warning box (like you see on the fredtool page's cfw check). People following these pages may also not necessarily be on the latest firmware (even if it's quite likely).
