### ISSUE TITLE
Providing cartupdated version crossing two releases can lead to useless Soundhax guide

### ISSUE THREAD

**Issue by KamilaBorowska** [hacks-guide/Guide_3DS#2279]
**Pages with issue(s)**

https://3ds.hacks.guide/get-started

**Description of the issue(s)**

Providing a version like `7.1.0-0E` will lead to soundhax guide that may not work (it's complicated, as some cart update partitions provided Nintendo 3DS Sounds updates, and some didn't).

I think the guide should be either updated to handle those versions (there is a special build specifically for those versions - https://github.com/nedwill/soundhax/pull/114), or soundhax shouldn't be suggested when NVer is between 0 and 4 and CVer is at least 5.0.0 (indicating cart update).

**Comment by lifehackerhansol** [comment]
@danny8376 what do you propose? Since you are primarily the one messing with it.

**Comment by lifehackerhansol** [comment]
I am slightly hesitant on adding yet another soundhax page. We tried this previously and it became a total mess so we said no.
At the same time, I can't think of a user-friendly way to explain the myriad of firmware version combinations possible.

One could maybe attempt safecerthax (on N3DS this is a non-issue, people should just system update and do skaterhax).

**Comment by lilyuwuu** [comment]
In the majority of cases N3DS wouldn't have cart updated from such lower firmwares anyway

**Comment by danny8376** [comment]
I do agree that don't make soundhax complicated. when normal soundhax doesn't work, try safecerthax first will be more reasonable imo as there's no variation, so it's simply hit or miss (more likely to just work? no idea tbh). only when safecerthax isn't feasible (broken button), i'll be more willing to suggest trying those non-standard soundhax.
(Also, i do see multiple cases that every possible soundhax file simply doesn't work at all, so it's really a total mess.)

Probably do hardware test for those -0 ~ -4 / pre-5.0 consoles and do safecerthax when possible, fall back to soundhax otherwise?
However, i don't really know it's more common to have cartupdate ones for those early versions or it's the other way around. It might not worth the hassle to do the branch and simply make them go discord for their "weird rare?" case.

Oh, pre-2.1/v0 app seems to be easily identifiable, as they seems to be always say unplayable when used post-2.1 file, and crash only with pre-2.1 non franken file. However, again, not really confident about it as again, those firmware seems to be a huge mess.
