### ISSUE TITLE
Safecerthax guide suggests Seedminer as an alternative

### ISSUE THREAD

**Issue by xfix** [hacks-guide/Guide_3DS#2280]
**Pages with issue(s)**

https://3ds.hacks.guide/installing-boot9strap-(safecerthax)

**Description of the issue(s)**

The guide says the following:

> If the camera did NOT appear, you cannot follow this method. If this is the case, use [Seedminer](https://3ds.hacks.guide/seedminer) instead.

Seedminer definitely won't work as the current guide requires 11.16 which cannot be used when using Safecerthax-compatible version. It probably should point to Mii Mining instead.

**Comment by lifehackerhansol** [comment]
Mii mining doesn't work either. You need to be on 11.14 at minimum for it due to fredtool requiring specific NFIRM.

This might be a black hole in the guide path. It might be better for users to join the server.

**Comment by lilyuwuu** [comment]
SSLoth-Browser is also subject to this issue, so this issue actually affects two pages. I'll update the warning accordingly but leaving this open until we have a proper fix on the guide.

**Comment by TheMasterOfMike** [comment]
> SSLoth-Browser is also subject to this issue, so this issue actually affects two pages. I'll update the warning accordingly but leaving this open until we have a proper fix on the guide.

hi, I'm back from the dead (again)

This shouldn't be an issue for SSLoth-Browser since it uses universal-otherapp (and therefore, goes straight to SafeB9SInstaller, making dead shoulder buttons a non-issue) (which also makes this a mostly non-issue for 11.4-11.13)

And then for 11.14, unless there's something I'm missing, https://3ds.hacks.guide/installing-boot9strap-(fredtool-legacy) says it works for 11.14, which should mean that you'd be able to Mii Mine, then follow bb3, then follow fredtool using b9stool 6.0.1

Really, this only ends up being an issue for people either going out of their way to use safecerthax on 11.4-11.13, or people who somehow cart updated with a (relatively) newer cart to 11.4-11.9 (as iirc 11.9.0 was the last cart update version, correct me if I'm wrong on that though)

**Comment by lilyuwuu** [comment]
The issue is more with linking Seedminer, which has since been resolved. Keeping this issue open until we resolve the situation for ppl with broken shoulders (safecerthax) and people with cart updates (ssloth).
