### ISSUE TITLE
Use MSET9 instead of Seedminer

### ISSUE THREAD

**Issue by Anonymous941** [hacks-guide/Guide_3DS#2388]
MSET9 is compatible with every version that Soundhax doesn't run on, and is no longer in beta.  While it isn't as easy as some of the other exploits as it requires exact instructions to be followed and doesn't work on macOS, it's still much better then Seedminer for a number of reasons:

* Time: Seedminer has a huge amount of more steps to be preformed when chained with BannerBomb3 and menuhax.  This causes a long installation time on both the computer and the console
* Processing power: Seedminer requires brute-force power that isn't huge, but also certainly isn't trivial, especially on old computers
* Ease: while MSET9 requires not pressing the touch screen or any buttons to be pressed, Seedminer has a lot of steps that could be difficult to preform
* Requirement of Internet: Seedminer requires that a friend code be added on the 3DS, which requires a working Internet connection on the console and the console being unbanned
* Requirement of upgrading: this isn't a problem of Seedminer, but it's still worth mentioning (and I don't think needs a separate issue): on the New 3DS, you are required to upgrade to the latest firmware if you have most firmware versions, which requires Internet and also has a small chance of causing a brick, especially if CFW was installed before

For these reasons, I think it would be better to recommend MSET9 by default, and then link to the Seedminer methods as an alternative

**Comment by lilyuwuu** [comment]
Honestly not totally against this. Some preliminary thoughts (I'm gathering some thoughts over in #guide-meta on Nintendo Homebrew, and of course anyone else is free to comment here too):

- MSET9 certainly has matured enough and is generally faster and less annoying for us to deal with
- Bruteforcing doesn't have to be done by the end-user through miner services like [BFM](https://seedminer.hacks.guide) and [MovableQ](https://cm360.xyz/movableq/) (#2381)
- MSET9's biggest current drawback is OS support (macOS, which can be worked around, and iOS/iPadOS which most likely cannot)
    - About half of guide visits come from mobile, though we can't know how many people are doing things on a computer and just following along on their phone or whatever
- Seedminer requires Internet, while Seedminer (Mii) doesn't. That being said Seedminer minus the Mii will be dead in \*checks clock* five months anyway.
- I guess there's a hypothetical chance of bricking from a system update, but that's just... pretty much every system update ever, and if it wasn't something that could be restored via Safe Mode there was probably some other issue anyway. Basically I don't think we're going to end up in a Switch 17.0.0 situation sort of thing
- It isn't really possible to link to Seedminer as an alternative from the MSET9 page as-is because we route it for 11.17 users and people who are on 11.17 wouldn't be able to follow the Seedminer methods

**Comment by lifehackerhansol** [comment]
OS support is a *huge* blocker. I'd rather switch Seedminer to Mii mining before using MSET9.

**Comment by Anonymous941** [comment]
> I guess there's a hypothetical chance of bricking from a system update, but that's just... pretty much every system update ever, and if it wasn't something that could be restored via Safe Mode there was probably some other issue anyway. Basically I don't think we're going to end up in a Switch 17.0.0 situation sort of thing

Okay, good point

> It isn't really possible to link to Seedminer as an alternative from the MSET9 page as-is because we route it for 11.17 users and people who are on 11.17 wouldn't be able to follow the Seedminer methods

Maybe at least MSET9 could be listed as an alternative to Seedminer for the time being?
