### ISSUE TITLE
Recommend backup before CFW install?

### ISSUE THREAD

**Issue by mariomadproductions** [hacks-guide/Guide_3DS#2435]
It might be worth suggesting people backup their NAND using before they install CFW, so that they have a clean backup. Currently the guide tells the user to do it afterwards.

**Comment by danny8376** [comment]
well, it's literally impossible to do it before modded
also, there's literally no point of doing it before modded

**Comment by lilyuwuu** [comment]
it could be possible (have a payload that backs up nand take the place of safeb9sinstaller) but it would generally be impractical

**Comment by mariomadproductions** [comment]
> it could be possible (have a payload that backs up nand take the place of safeb9sinstaller) but it would generally be impractical

Could the payload just be GodMode9? That could be used to backup then run safeb9sinstaller, right? That seems reasonably practical, unless I'm misunderstanding.

**Comment by ihaveamac** [comment]
It's easier and better to get boot9strap installed first and then make a backup. No real need to do it before.

**Comment by lilyuwuu** [comment]
it's impractical in that it's asking users to do a lot (run a backup routine that will take a while and may not even be successful or may not complete due to insufficient space).

For practical purposes a 'clean backup' is any console where no major modifications (i.e. modified uniques, region change) are made; any backup made at this point (especially when finalizing setup is automated and thus cannot end up in a scenario where a user accidentally ends up with a nand backup) would effectively be as clean as pre-b9s

For a dev console I would agree with backing up first, but this guide doesn't cover dev units

**Comment by mariomadproductions** [comment]
IMO, its a good thing to do for retail too, not just dev units. Sometimes factory apps are found, or maybe the owner might want to restore it to pre-hacked state before reselling, and just for preserving the original state in general. But I guess it should be an optional thing, yeah.

**Comment by ihaveamac** [comment]
"owner might want to restore it to pre-hacked state before reselling" is what we have an uninstall guide for. If they have a NAND backup from the time they did Finalizing Setup, that is as close to stock as possible.

We probably won't have it be an "optional" part because the more options people have to decide on, the more complicated it gets. So we only support one guide path where possible, and multiple only when it's necessary.

**Comment by mariomadproductions** [comment]
Yeah I understand the need to keep it as simple as possible.
